=== Razanio/epam-labs/xml-parser/src/main/java/com/epam/courses/resourses/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/components"
        xmlns:tns="http://www.example.org/components" elementFormDefault="qualified">
    <element name="components">
        <complexType>
            <sequence>
                <element name="component" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="origin" type="string"/>
                            <element name="price" type="double"/>
                            <element name="feature">
                               <complexType>
                                  <sequence>
                                      <element name="peripheral" type="boolean"/>
                                      <element name="energy-consumption" type="double"/>
                                      <element name="cooler" type="boolean"/>
                                      <element name="purpose">
                                          <simpleType>
                                              <restriction base="string">
                                                  <enumeration value="OUTPUT" />
                                                  <enumeration value="INPUT" />
                                                  <enumeration value="OUTPUTINPUT" />
                                                  <enumeration value="MULTIMEDIA" />
                                                  <enumeration value="MEMORY" />
                                                  <enumeration value="COMPUTINGLOGIC" />
                                              </restriction>
                                          </simpleType>
                                      </element>
                                      <element name="port" minOccurs="0">
                                          <complexType>
                                              <sequence>
                                                  <element name="HDMI" minOccurs="0">
                                                      <simpleType>
                                                          <restriction base="nonNegativeInteger"/>
                                                      </simpleType>
                                                  </element>
                                                  <element name="COM" minOccurs="0">
                                                      <simpleType>
                                                          <restriction base="nonNegativeInteger"/>
                                                      </simpleType>
                                                  </element>
                                                  <element name="USB" minOccurs="0">
                                                      <simpleType>
                                                          <restriction base="nonNegativeInteger"/>
                                                      </simpleType>
                                                  </element>
                                                  <element name="LPT" minOccurs="0">
                                                      <simpleType>
                                                          <restriction base="nonNegativeInteger"/>
                                                      </simpleType>
                                                  </element>
                                              </sequence>
                                          </complexType>
                                      </element>
                                  </sequence>
                               </complexType>
                            </element>
                            <element name="critical" type="boolean"/>
                        </sequence>
                        <attribute name="id" type="string" use="required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== Razanio/epam-labs/xml-parser/src/main/java/com/epam/courses/domain/backup/components.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.org/components" xsi:schemaLocation="http://www.example.org/components components.xsd">
    <component id="a&amp;1">
        <name>CPU Intel Core i3-10100F</name>
        <origin>USA</origin>
        <price>337.99</price>
        <feature>
            <peripheral>false</peripheral>
            <energy-consumption>65</energy-consumption>
            <cooler>false</cooler>
            <purpose>COMPUTINGLOGIC</purpose>
        </feature>
        <critical>true</critical>
    </component>
    <component id="a&amp;2">
        <name>RAM Samsung 8GB DDR4</name>
        <origin>South Korea</origin>
        <price>144.99</price>
        <feature>
            <peripheral>false</peripheral>
            <energy-consumption>3</energy-consumption>
            <cooler>false</cooler>
            <purpose>MEMORY</purpose>
        </feature>
        <critical>true</critical>
    </component>
    <component id="a&amp;3">
        <name>Palit GeForce GTX 1660 Super GP 6GB GDDR6</name>
        <origin>USA</origin>
        <price>1949.49</price>
        <feature>
            <peripheral>true</peripheral>
            <energy-consumption>450</energy-consumption>
            <cooler>true</cooler>
            <purpose>COMPUTINGLOGIC</purpose>
            <port>
                <hdmi>2</hdmi>
                <usb>1</usb>
            </port>
        </feature>
        <critical>false</critical>
    </component>
    <component id="a&amp;4">
        <name>Seagate Skyhawk 6TB</name>
        <origin>USA</origin>
        <price>558.99</price>
        <feature>
            <peripheral>true</peripheral>
            <energy-consumption>9.6</energy-consumption>
            <cooler>false</cooler>
            <purpose>MEMORY</purpose>
        </feature>
        <critical>false</critical>
    </component>
    <component id="a&amp;5">
        <name>Acoustic system Sony SS-CS5</name>
        <origin>Japan</origin>
        <price>488.67</price>
        <feature>
            <peripheral>true</peripheral>
            <energy-consumption>100</energy-consumption>
            <cooler>true</cooler>
            <purpose>MULTIMEDIA</purpose>
            <port>
                <usb>2</usb>
            </port>
        </feature>
        <critical>false</critical>
    </component>
    <component id="a&amp;6">
        <name>Monitor Acer Predator X34</name>
        <origin>Taiwan</origin>
        <price>3761.46</price>
        <feature>
            <peripheral>true</peripheral>
            <energy-consumption>70</energy-consumption>
            <cooler>false</cooler>
            <purpose>OUTPUTINPUT</purpose>
            <port>
                <hdmi>4</hdmi>
                <usb>1</usb>
                <lpt>3</lpt>
            </port>
        </feature>
        <critical>false</critical>
    </component>
</components>
